
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package esercitazione5;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CHAR_CONST = 53;
  public static final int POW = 34;
  public static final int CHAR = 10;
  public static final int GE = 41;
  public static final int CASE = 50;
  public static final int INTEGER_CONST = 55;
  public static final int SEMI = 3;
  public static final int INT = 7;
  public static final int OUT = 13;
  public static final int FOR = 14;
  public static final int MINUS = 31;
  public static final int WRITE = 21;
  public static final int NOT = 44;
  public static final int AND = 42;
  public static final int LT = 38;
  public static final int RPAR = 24;
  public static final int OR = 43;
  public static final int BOOL = 9;
  public static final int COMMA = 4;
  public static final int DIV = 33;
  public static final int LOOP = 19;
  public static final int PLUS = 30;
  public static final int ASSIGN = 26;
  public static final int MAIN = 2;
  public static final int IF = 15;
  public static final int WRITELN = 22;
  public static final int ID = 51;
  public static final int LE = 39;
  public static final int EOF = 0;
  public static final int RETURN = 27;
  public static final int TRUE = 28;
  public static final int error = 1;
  public static final int PIPE = 5;
  public static final int VOID = 11;
  public static final int EQ = 36;
  public static final int SWITCH = 49;
  public static final int LBRACK = 46;
  public static final int FLOAT = 45;
  public static final int TIMES = 32;
  public static final int COLON = 25;
  public static final int ELSE = 16;
  public static final int RBRACK = 47;
  public static final int READ = 20;
  public static final int TO = 18;
  public static final int WHILE = 17;
  public static final int STR_CONCAT = 35;
  public static final int REAL_CONST = 54;
  public static final int THEN = 48;
  public static final int NE = 37;
  public static final int LPAR = 23;
  public static final int STRING = 8;
  public static final int DEF = 12;
  public static final int FALSE = 29;
  public static final int STRING_CONST = 52;
  public static final int GT = 40;
  public static final int VAR = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "SEMI",
  "COMMA",
  "PIPE",
  "VAR",
  "INT",
  "STRING",
  "BOOL",
  "CHAR",
  "VOID",
  "DEF",
  "OUT",
  "FOR",
  "IF",
  "ELSE",
  "WHILE",
  "TO",
  "LOOP",
  "READ",
  "WRITE",
  "WRITELN",
  "LPAR",
  "RPAR",
  "COLON",
  "ASSIGN",
  "RETURN",
  "TRUE",
  "FALSE",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "POW",
  "STR_CONCAT",
  "EQ",
  "NE",
  "LT",
  "LE",
  "GT",
  "GE",
  "AND",
  "OR",
  "NOT",
  "FLOAT",
  "LBRACK",
  "RBRACK",
  "THEN",
  "SWITCH",
  "CASE",
  "ID",
  "STRING_CONST",
  "CHAR_CONST",
  "REAL_CONST",
  "INTEGER_CONST"
  };
}

